[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -q
norecursedirs = .venv .git .idea .pytest_cache data docs __pycache__ pytest-cache-files-*